export const US_HEADER = [
  'date/time',
  'settlement id',
  'type',
  'order id',
  'sku',
  'description',
  'quantity',
  'marketplace',
  'account type',
  'fulfillment',
  'order city',
  'order state',
  'order postal',
  'tax collection model',
  'product sales',
  'product sales tax',
  'shipping credits',
  'shipping credits tax',
  'gift wrap credits',
  'giftwrap credits tax',
  'Regulatory Fee',
  'Tax On Regulatory Fee',
  'promotional rebates',
  'promotional rebates tax',
  'marketplace withheld tax',
  'selling fees',
  'fba fees',
  'other transaction fees',
  'other',
  'total',
];

export const JP_HEADER = [
  '日付/時間',
  '決済番号',
  'トランザクションの種類',
  '注文番号',
  'SKU',
  '説明',
  '数量',
  'Amazon 出品サービス',
  'フルフィルメント',
  '市町村',
  '都道府県',
  '郵便番号',
  '税金徴収型',
  '商品売上',
  '商品の売上税',
  '配送料',
  '配送料の税金',
  'ギフト包装手数料',
  'ギフト包装クレジットの税金',
  'Amazonポイントの費用',
  'プロモーション割引額',
  'プロモーション割引の税金',
  '源泉徴収税を伴うマーケットプレイス',
  '手数料',
  'FBA 手数料',
  'トランザクションに関するその他の手数料',
  'その他',
  '合計',
];

export const US_CHECKOUT_HEADER = [
  '出貨廠商',
  '商品總金額',
  '其他應收',
  '多扣金額',
  'Amazon手續費',
  'FBA進倉國內標籤費',
  'FBA倉庫費',
  '月租費',
  '廣告費',
  '棄置費用',
  '退貨費用',
  '亞馬遜庫存賠償',
  '總收款金額',
];

export const JP_CHECKOUT_HEADER = [
  '出貨廠商',
  '商品總金額( 商品売上+稅金 )',
  '其他應收( 配送料+ギフト包装手数料+其他稅金+配送料の税金 )',
  '其他應付( プロモーション割引額+プロモーション割引の税金 +Amazonポイント)',
  'Amazon手續費( 手数料+FBA 手数料 )',
  '多渠道配送( 発送手数料 )',
  'FBA倉庫費( FBA保管手数料 )',
  '月租費( 月額登録料 )',
  '長期庫存費( FBA長期在庫保管手数料 )',
  '廣告費( 広告費用 + 表示価格+数量限定タイムセール手数料 )',
  '棄置費( FBA在庫の廃棄手数料 )',
  '退貨費用( 返金 )',
  '庫存調整( FBA在庫の返金 )',
  '其他( その他 )',
  '臨時費用(多渠道)',
  '總收款金額( 合計 )',
];
